/** 工具名 → 中文短标签，气泡里显示“正在做什么”。 */
export const TOOL_LABELS = {
  bash: '跑命令',
  read: '读文件',
  write: '写文件',
  edit: '改代码',
  glob: '找文件',
  grep: '搜代码',
  todo_write: '排计划',
  subagent: '派分身',
  subagent_fork: '派分身',
  web_search: '上网查',
  web_fetch: '读网页',
  kb_search: '翻知识库',
  kb_rag: '查知识库',
  kb_ingest: '入库文献',
  ask_user_question: '等你回话',
  create_goal: '立目标',
  update_goal: '更新目标',
  present: '交付文件',
  workflow: '编排分身',
  ralph: 'Ralph 循环',
  pdf_create: '生成 PDF',
  docx_create: '生成文档',
  xlsx_write: '生成表格',
  pptx_create: '生成幻灯片',
  auto_cite: '加引用',
  search_papers: '查文献',
  sci_draw: '画图',
}
