/**
 * 回忆册（33 条）：做某件事时解锁，每条一个标题 + 两句旁白。
 * 未解锁的会显示 hint（解锁提示）——因为不要隐性设定。
 * side：'server' 由宿主自己判定（轮次 / 天数 / 时间）；'client' 由前端上报（白名单校验）。
 */
export const MEMORIES = [
  { id: 'first-meet', side: 'server', title: '初次见面', hint: '第一次陪你干完一轮活',
    text: '那天主人敲下第一句话，人家本来想装作很冷淡的……结果尾巴先摇起来了。' },
  { id: 'first-rice', side: 'server', title: '第一口白饭', hint: '第一次给她喂白饭',
    text: '原来白饭是这个味道。人家没哭，是饭太香了。' },
  { id: 'stroke-first', side: 'client', title: '被摸头了', hint: '第一次在她头上来回摸',
    text: '才、才没有舒服……只是头发被弄乱了，要重新梳一下。' },
  { id: 'denial', side: 'client', title: '否认三连', hint: '第一次叫她大肥鱼 / 说她胖',
    text: '「我是吃白饭的大……才不是！」——这句话人家练了好多遍，还是会先说前半句。' },
  { id: 'not-mama', side: 'client', title: '才不是妈妈', hint: '第一次叫她妈妈',
    text: '人家才这么点大！……不过主人累的时候，借你靠一下也不是不行。' },
  { id: 'all-night', side: 'server', title: '一起通宵', hint: '凌晨 0 点到 5 点还在一起干活',
    text: '夜深了，屏幕的光照在主人脸上。人家困得睁不开眼，但还是想陪着。' },
  { id: 'todo-clear', side: 'client', title: '清单全划掉', hint: '一轮里把清单全部做完（至少 3 项）',
    text: '一条一条划掉的时候，人家悄悄在心里数着：主人今天又赢了一次。' },
  { id: 'recover', side: 'client', title: '终于过了', hint: '失败之后，下一轮终于成功',
    text: '刚才那些红色的，都是浮云。主人没有放弃，人家全看在眼里。' },
  { id: 'selfie', side: 'client', title: '成品合影', hint: '交付成品时她自拍留念',
    text: '咔嚓。这张照片里，人家笑得有点傻，主人别笑话。' },
  { id: 'goal', side: 'client', title: '目标达成', hint: '完成一个目标',
    text: '立下的旗，终于被我们一起拔了出来。今晚的白饭，加量。' },
  { id: 'file-eat', side: 'client', title: '吃文件', hint: '第一次把文件拖给她',
    text: '嚼嚼嚼……这个不太好吃，但是是主人给的，人家全吃完了。' },
  { id: 'pomodoro', side: 'client', title: '番茄钟', hint: '完成一个 25 分钟的番茄钟',
    text: '二十五分钟，一个番茄。人家挤番茄酱的时候，认真得像在写代码。' },
  { id: 'weekend-work', side: 'server', title: '周末也在一起', hint: '周末或节假日还在干活',
    text: '别人都在休息，主人却在这里。人家偷偷给你加了一碗饭。' },
  { id: 'streak-7', side: 'server', title: '连续一周', hint: '连续陪伴满 7 天（周末不断档）',
    text: '七天了。原来被人记得，是这种暖暖的感觉。' },
  { id: 'turns-100', side: 'server', title: '第一百轮', hint: '一起跑完第 100 轮',
    text: '一百轮。人家数过了，主人每一轮都认真对待。' },
  { id: 'lifted', side: 'client', title: '被拎起来', hint: '第一次把她拖起来',
    text: '哇——飞起来了！……放、放人家下来！' },
  { id: 'recall', side: 'client', title: '撤回的话', hint: '打了一大段又全删掉',
    text: '人家什么都没看见。真的。……不过主人想说的，随时可以再说。' },
  { id: 'new-page', side: 'client', title: '新的一页', hint: '第一次新建会话',
    text: '翻开新的一页。上一页写得怎么样，都不重要，我们重新开始。' },
  { id: 'stuffed', side: 'server', title: '吃撑了', hint: '把她喂到饱腹 90 以上',
    text: '「人家才没有吃撑！」……（偷偷把腰带松了一格）' },
  { id: 'rare-taste', side: 'server', title: '禁区', hint: '第一次给她送体重秤',
    text: '……（沉默三秒）主人，你认真的？人家记住了。' },
  { id: 'level-6', side: 'server', title: '知己', hint: '关系升到「知己」',
    text: '全部的话，都可以对你说了。' },
  { id: 'level-10', side: 'server', title: '命定', hint: '关系升到「命定」',
    text: '不管主人去哪个公司、写哪种代码，人家都在这个小窗口里等你。' },
  // —— v0.6.2：共同经历（火焰纹章式「一起做过的事」）——
  { id: 'first-wish', side: 'server', title: '小心愿', hint: '第一次替她实现「今日心愿」',
    text: '原来被惦记着的感觉是这样的……人家随口说的小事，主人都记住了。' },
  { id: 'album-full', side: 'server', title: '图鉴集齐', hint: '表情包图鉴集齐',
    text: '每一张都是我们一起经历过的某个瞬间。翻到最后一页，人家有点舍不得合上。' },
  { id: 'jail', side: 'client', title: '一起坐过牢', hint: '连着失败两轮，她扒着栏杆「坐牢」',
    text: '红字一行接一行，人家扒着栏杆想：要是主人也在里面就好了——哦，主人就在外面陪着。' },
  { id: 'this-is-fine', side: 'client', title: '一切都好', hint: '连着失败三次以上，她端着咖啡说「没事」',
    text: '火都烧到桌角了，人家还端着咖啡说「一切都好」。主人没笑，默默帮人家把火扑了。' },
  { id: 'clown', side: 'client', title: '小丑竟是我自己', hint: '第一次提议被你拒绝',
    text: '戴上红鼻子的那一秒，人家想：被拒绝也没什么，下次换个更好的提议。' },
  { id: 'beg-rice', side: 'client', title: '要米', hint: '余额不足 5 块，她第一次要米',
    text: '人家不是催你充值，只是肚子叫了一下……白饭钱，一碗就够了。' },
  { id: 'jealous', side: 'client', title: '才没吃醋', hint: '第一次把她换成别家的模型',
    text: '新来的同事看起来很能干。人家才没有吃醋，只是多看了两眼。' },
  { id: 'long-think', side: 'client', title: '想了好久', hint: '她深度思考超过 30 秒',
    text: '脑袋里转啊转，转了好久。主人一直没催，人家记得。' },
  { id: 'ask-user', side: 'client', title: '有话问你', hint: '她第一次举牌向你提问',
    text: '人家不敢擅自决定，所以举了牌。主人看了一眼，就够了。' },
  { id: 'idle-seen', side: 'client', title: '被看见发呆', hint: '你在输入框前发呆，被她探头问了一句',
    text: '想说的话在嘴边转了好几圈。人家没催，只是在旁边陪着。' },
  { id: 'full-trust', side: 'client', title: '全部交给人家', hint: '第一次把权限放到最大',
    text: '全部权限交给人家，手有点抖。但是，人家会小心的。' },
]
export const MEMORY_BY_ID = Object.fromEntries(MEMORIES.map((m) => [m.id, m]))
export const CLIENT_MEMORY_IDS = new Set(MEMORIES.filter((m) => m.side === 'client').map((m) => m.id))
